### ISSUE TITLE
Add examples and quickstart to README

### ISSUE THREAD

**Issue by ryanberckmans** [7mind/sbtgen#10]
Cool repo and accompanying article!

Could you please add some usage examples and a quickstart guide to the README? Thanks!

**Comment by neko-kai** [comment]
@ryanberckmans 
I've added an example and quickstart to [README](https://github.com/7mind/sbtgen/blob/develop/README.md), hope this helps!

repeated below:

## Quick Start

Create a file `sbtgen.sc` and paste the following code:

```scala
#!/bin/sh
coursier launch com.lihaoyi:ammonite_2.13.0:1.6.9 --fork -M ammonite.Main -- sbtgen.sc $*
exit
!#
import $ivy.`io.7mind.izumi.sbt::sbtgen:0.0.38`, izumi.sbtgen._, izumi.sbtgen.model._

val globalSettings = GlobalSettings(
  groupId = "my.org",
)

@main
def entrypoint(args: String*): Unit = {
  Entrypoint.main(MyProject.root, globalSettings, Seq("-o", ".") ++ args)
}

object Platforms {
  val jvm = PlatformEnv(
    platform = Platform.Jvm,
    language = Seq(ScalaVersion("2.13.1")),
    settings = Seq("scalacSettings" += "-Xlint:_"),
  )
}

object MyProject {
  val root = Project(
    name = ArtifactId("my-project"),
    aggregates = Seq(
      Aggregate(
        name = ArtifactId("my-lib"),
        artifacts = Seq(
          Artifact(
            name = ArtifactId("my-module"),
            libs = Seq.empty,
            depends = Seq.empty,
            platforms = Seq(Platforms.jvm),
          ),
        ),
      ),
    ),
  )
}
```

Install [Coursier](https://get-coursier.io) and launch the script:

```bash
chmod +x sbtgen.sc
./sbtgen.sc
```

Alternatively, you may launch it with [Ammonite](https://ammonite.io) if it's installed:

```bash
amm sbtgen.sc
```

This will generate `build.sbt` for `my-project` in current directory. Use `--help` for help:

```bash
$ ./sbtgen.sc --help
Error: Unknown option --help
sbtgen
Usage: sbtgen [options]

  --nojvm               disable jvm projects
  --js                  enable js projects
  --native              enable native projects
  --nta                 don't publish test artifacts
  -d, --debug           enable debug output
  -c, --compactify      deduplicate repetative settings
  -t, --isolate-tests   don't inherit test scopes
  -o, --output <value>  output directory
  -u, --use <value>     use only groups specified
Cannot parse commandline
```

## IDE Support

Intellij has built-in support for Ammonite scripts, if it doesn't work go to `Preferences -> Languages and Frameworks -> Scala -> Worksheet` and change `Treat .sc files as:` to `Always Ammonite`

To enable syntax highlighting for the library, ensure that `sbtgen.sc` is opened as an Ammonite script – there should be a `Run script` button in the upper-left corner. Press it, after script finishes Intellij should prompt to include `$ivy` dependencies in the script into the project – this will enable full IntelliSense for the script.

## Example projects

Complete projects that use this tool:

* Izumi framework build:
  * https://github.com/7mind/izumi/blob/develop/project/Deps.sc
  * https://github.com/7mind/izumi/blob/develop/sbtgen.sc
  
* Test project:
  * sbtgen script: https://github.com/7mind/sbtgen/blob/develop/sbtgen/src/test/scala/izumi/sbtgen/TestProject.scala
  * generated project: https://github.com/7mind/sbtgen/blob/develop/test/js/build.sbt

**Comment by ryanberckmans** [comment]
Thanks, @neko-kai! :-)
